### ISSUE TITLE
Publish on npm?

### ISSUE THREAD

**Issue by fonsp** [andreypopp/lang-julia#1]
Hey andrey!

It would help me out if you could publish this package, together with https://github.com/lezer-parser/julia to npm :) Installing this package and lezer-julia directly from github gave me build issues.

**Comment by andreypopp** [comment]
Hi Fons!

I can do this tomorrow, need to upgrade to newest lezer/codemirror first (lezer recently had [backward incompatible changes](https://discuss.codemirror.net/t/lezer-0-15-0-release/3434) and I need to assess everything works after that).

**Comment by andreypopp** [comment]
Published [lezer-julia](https://www.npmjs.com/package/lezer-julia) and [lang-julia](https://www.npmjs.com/package/lang-julia).
